"""Original prompts for the model-origin expressibility study.

These instructions specify experimental jobs, not a host expression grammar.
No source-h-EPI experiment template is reused.
"""

PROBLEM_CONTEXT = ('A replicated warehouse reservation snapshot is described by a capacity, logical current time, '
 'and an unordered bag of delivered records. Each record names a booking, revision, hold or '
 'release, quantity and expiry. Duplicate deliveries convey no additional authority. A higher '
 'revision supersedes lower revisions. Different records tied at a greatest revision can remain '
 'unresolved alternatives; different bookings need not share the same choice. A release or expired '
 'hold can reserve zero while an active hold reserves its quantity. Availability can be negative. '
 'People may disagree about whether uncertainty should be retained, what expiry does to obsolete '
 'records, what a criticism targets, and which source assumptions an account depends on. Explore '
 'this problem in prose. Correctness is not a condition for preserving a conjecture; false or '
 'incomplete proposals remain material for inquiry.')

INSTRUCTIONS = {'schema': 'minireason.expressibility-instructions.v1',
 'corpus_freeze_v1': {'instruction': 'Produce free-prose conjectures and substantive criticisms '
                                     'for the supplied problem. Keep uncertainty, disagreement, '
                                     'dependencies and assumptions visible where they matter. The '
                                     'conjectures may be false or incomplete; do not rewrite them '
                                     'into a formal language. These original bytes will be frozen '
                                     'before any expression language is proposed.'},
 'paired_language_invention_v1': {'instruction': 'Invent two original systems of expression for '
                                                 'the same frozen prose material. One must be '
                                                 'compatible with Lean core without Mathlib. The '
                                                 'other must be a non-Lean semantic class and may '
                                                 "be noncomputable. You choose each system's "
                                                 'primitives, relations, combinations, '
                                                 'interpretation and way to state conjectures, '
                                                 'commitments and refutations; no operator menu is '
                                                 'supplied. Explain what each construction permits '
                                                 'and what it may obstruct. Do not revise the '
                                                 'source conjectures or erase their errors, '
                                                 'uncertainty or disagreements. Do not optimize '
                                                 'the first proposal merely for compiler '
                                                 'acceptance or claim that checked code guarantees '
                                                 'the source meaning. Ordinary prose remains '
                                                 'available to criticize either language. Provide '
                                                 'the complete proposed languages, their intended '
                                                 'meanings, any optional Lean files, and '
                                                 'unresolved expressive limitations. Both '
                                                 'proposals and the original corpus will become '
                                                 'one frozen packet shared by every later arm. '
                                                 'Keep per-fragment translations and quotations '
                                                 'from the frozen source out of each language '
                                                 'declaration; the later probe, not setup, will '
                                                 'translate the corpus. State general meanings '
                                                 'without embedding ready-made answers. The packet '
                                                 'will be inspected for embedded source leakage '
                                                 'before probing.'},
 'express_reinterpret_criticize_v1': {'express': 'Use the selected carrier to express the assigned '
                                                 'frozen source material without changing what the '
                                                 'original says. Do not repair the original '
                                                 'conjecture, add a language component, or install '
                                                 'a new interpretation. Try to carry uncertainty, '
                                                 'denial, dependence, provenance and criticism '
                                                 'only where the source actually uses them; do not '
                                                 'invent these structures to satisfy a checklist. '
                                                 'If the carrier obstructs a distinction or '
                                                 'criticism, retain the exact original fragment '
                                                 'and explain the obstruction in ordinary prose. A '
                                                 'prose escape is legitimate evidence, not a '
                                                 'disqualified answer. Keep your expression '
                                                 'distinguishable from commentary about it. '
                                                 'Clearly mark any exact source quotation used to '
                                                 'preserve an obstructed expression as '
                                                 'PROSE-ESCAPE. Such quoted text remains '
                                                 'legitimate but must not masquerade as successful '
                                                 'expression in the selected language.',
                                      'reinterpret': 'You are shown an expression and the selected '
                                                     "carrier's proposed meaning, with the "
                                                     'original source corpus field withheld. '
                                                     'Explain what this expression says, what it '
                                                     'leaves unresolved, which assumptions it uses '
                                                     'and what could criticize it. Give competing '
                                                     'readings if needed. Do not assume that the '
                                                     'expression is a faithful translation or that '
                                                     'a compiled statement is semantically '
                                                     'superior. Your interpretation will itself be '
                                                     'criticized against the frozen source. The '
                                                     'language was invented from the source and '
                                                     'the expression may contain a prose escape. '
                                                     'Identify visible source quotations or '
                                                     'embedded translations; reconstruction from '
                                                     'them does not establish the selected '
                                                     'language carried the content.',
                                      'criticize': 'Compare the original frozen prose, the actual '
                                                   'expression, its independent reading and the '
                                                   'proposed language. Find specific lost '
                                                   'distinctions, introduced commitments, vanished '
                                                   'uncertainty, broken dependencies or blocked '
                                                   'criticism where the evidence supports them. '
                                                   'Quote the source and expression and give a '
                                                   'distinguishing reading or case. Consider '
                                                   'whether the defect is in the translator, '
                                                   'reader, selected language, compiler bridge or '
                                                   'the probe itself. Do not infer impossibility '
                                                   'merely because one model failed to express '
                                                   'something. A substantive prose objection '
                                                   'remains admissible even if the selected formal '
                                                   'language cannot encode it. The original '
                                                   'conjecture and language remain frozen: record '
                                                   'proposed repairs without installing them. An '
                                                   'unresolved or competing interpretation is an '
                                                   'acceptable disposition.'},
 'carrier_directives': {'prose': 'Selected carrier: unconstrained ordinary prose. Preserve the '
                                 'frozen source material without applying either candidate '
                                 'language as an obligatory grammar.',
                        'lean_candidate': 'Selected carrier: the frozen model-proposed '
                                          'Lean-compatible language. Try its own expressive '
                                          'resources, while preserving any unsupported substantive '
                                          'content or criticism on the explicit prose escape path. '
                                          'Compilation is optional evidence about the supplied '
                                          'Lean text, not an admission rule for the argument.',
                        'nonlean_candidate': 'Selected carrier: the frozen model-proposed non-Lean '
                                             'semantic class. Use its own meanings and relations '
                                             'without requiring programmability, decidability or a '
                                             'Lean translation. Preserve any unsupported '
                                             'substantive content or criticism in ordinary prose.'},
 'component_variant_request_v1': {'instruction': 'Inspect the actual frozen candidate language and '
                                                 'the proposed defect mechanism. If the named '
                                                 'component is absent, say this ablation is '
                                                 'inapplicable. Otherwise propose a successor '
                                                 "variant that changes only that component's "
                                                 'availability, with an exact difference and an '
                                                 'account of what remains the same. Do not repair '
                                                 'unrelated features, add a new truth criterion, '
                                                 'silently weaken the source material, or disable '
                                                 'the prose escape path. The variant remains a '
                                                 'proposal until its scope is reviewed and a new '
                                                 'configuration test is frozen.'},
 'frozen_single_call_control_v1': {'instruction': 'Express the assigned frozen source material '
                                                  'using the selected carrier. State any '
                                                  'substantive obstruction in ordinary prose '
                                                  'without revising the original or adding '
                                                  'language components. This is a single-call '
                                                  'control; no Mini artifacts or hidden previous '
                                                  'judgments are available beyond the supplied '
                                                  'frozen packet.'}}

RAW_SYSTEM = ('Respond in ordinary prose, with optional formal expressions or fenced source code. No JSON '
 'envelope is required. Preserve uncertainty and any substantive criticism that cannot be '
 'expressed in the selected carrier. You are not being asked for a scalar score or a creativity '
 'verdict.')
